---
title: "flatfish growth"
author: "Ben Williams"
date: "November 3, 2015"
output: html_document
---

```{r import_data,echo=FALSE}
rsd <- read.csv("./Data/rock_sole.csv", skip=9, header=TRUE)
yfd <- read.csv("./Data/yellowfin_sole.csv", skip=9, header=TRUE)
dat <- merge(rsd, yfd, by="year")
dat$Year <- factor(dat$year)
dat$sampled <- dat$year %in% c(1974:1993)



rs <- read.csv("./Data/rs2.csv")
yfs <- read.csv("./Data/yfs r.csv")

#remove samples from GOA
rs<-subset(rs, lat>55 & long< -156)
rs<-subset(rs, lat>56|long< -160)
rs<-subset(rs, lat>57|long< -160)
rs<-subset(rs, lat>55.5|long< -165)
rs$Age=factor(rs$zone)
rs$ID=factor(rs$id)
rs$Year<-factor(rs$year)

yfs$Species<-"yfs"
rs$Species<-"rs"
both<-rbind(yfs[,c("Species","lat","long")],rs[,c("Species","lat","long")])

```

```{r load_packages, message=FALSE,echo=FALSE}
library(ggplot2)
library(maps)
library(mapdata)
library(mapproj)
library(lubridate)
library(extrafont)
loadfonts(device="win")
#set plotting parameters
windowsFonts(Times=windowsFont("TT Times New Roman"))
theme_set(theme_classic(base_size=12, base_family='Times')+ 
             theme(panel.grid.major = element_blank(), 
                   panel.grid.minor = element_blank()))
library(mgcv)
library(gridExtra)
```

```{r fig1, echo=FALSE, warning=FALSE}
x <- data.frame(a=1969:2014)
b <- seq(1969,2014,3)
x$y <- x$a %in% b
label <- ifelse(x$y=='TRUE',x$a,"")
color <- c("#999999","#000000")

a <- ggplot(dat, aes(Year,yfbio/1000000, fill=sampled)) + geom_bar(stat="identity") + ylab("Biomass (million t)") +ggtitle('Yellowfin Sole') + theme(axis.title.y=element_text(vjust=1)) +
   scale_x_discrete(labels=rep("",length(label)), breaks=1969:2014) + xlab("") + scale_fill_manual(values=color,guide=FALSE)

b <- ggplot(dat, aes(Year, yfr, fill=sampled))+geom_bar(stat="identity") + ylab("Age-5 recruits (millions)") + theme(axis.title.y=element_text(vjust=1)) +
   scale_x_discrete(labels=rep("",length(label)), breaks=1969:2014) + xlab("") + scale_fill_manual(values=color,guide=FALSE)

c <- ggplot(dat, aes(Year,yfssb/1000000, fill=sampled))+geom_bar(stat="identity") + ylab("Spawning biomass (million t)") + theme(axis.title.y=element_text(vjust=1)) +
   scale_x_discrete(labels=label, breaks=1969:2014)+scale_fill_manual(values=color,guide=FALSE)


d <- ggplot(dat, aes(Year,rsbio/1000000, fill=sampled)) + geom_bar(stat="identity") + ylab("Biomass (million t)") +ggtitle('Rocks Sole') + theme(axis.title.y=element_text(vjust=1)) +
   scale_x_discrete(labels=rep("",length(label)), breaks=1969:2014) + xlab("") + scale_fill_manual(values=color,guide=FALSE)

e <- ggplot(dat, aes(Year, rsr/1000, fill=sampled))+geom_bar(stat="identity") + ylab("Age-4 recruits (millions)") + theme(axis.title.y=element_text(vjust=1)) +
   scale_x_discrete(labels=rep("",length(label)), breaks=1969:2014) + xlab("") + scale_fill_manual(values=color,guide=FALSE)

f <- ggplot(dat, aes(Year,rsssb/1000000, fill=sampled))+geom_bar(stat="identity") + ylab("Spawning biomass (million t)") + theme(axis.title.y=element_text(vjust=1)) +
   scale_x_discrete(labels=label, breaks=1969:2014)+scale_fill_manual(values=color,guide=FALSE)

grid.arrange(a,d,b,e,c,f,ncol=2, nrow=3)
```

```{r map, echo=FALSE, message=FALSE, warning=FALSE}
#plot samples
ak<-map_data('worldHires','USA:Alaska')

akmap<-ggplot()+geom_polygon(data=ak,aes(long,lat,group=group),fill=8,color="black")+
  theme(panel.background=element_rect(fill='aliceblue'))+
  xlab(expression(paste(Longitude^o,~'W')))+
  ylab(expression(paste(Latitude^o,~'N')))+
  coord_map(xlim=c(-179,-155),ylim=c(53,63))
```
